{{- if .Values.fleetConfig.addOnConfigs }}
{{- $namespace := .Release.Namespace }}
{{- range .Values.fleetConfig.addOnConfigs }}
{{ $versionedName := printf "%s-%s" .name .version }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-addon-{{ $versionedName }}
  namespace: {{ $namespace }}
data:
  {{- if or (hasPrefix "http://" .manifests) (hasPrefix "https://" .manifests) }}
  manifestsURL: {{ .manifests }}
  {{- else }}
  manifestsRaw: |-
    {{- .manifests | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}