{{- if index .Values "fleetConfig" "enabled" }}
apiVersion: fleetconfig.open-cluster-management.io/v1alpha1
kind: FleetConfig
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: fleetconfig
  namespace: {{ .Release.Namespace }}
spec:
  timeout: {{ .Values.fleetConfig.timeout }}
  logVerbosity: {{ .Values.fleetConfig.logVerbosity }}
  {{- with .Values.fleetConfig.registrationAuth }}
  registrationAuth:
    driver: {{ .driver | quote }}
    {{- if .hubClusterARN }}
    hubClusterARN: {{ .hubClusterARN | quote }}
    {{- end }}
    {{- if .autoApprovedARNPatterns }}
    autoApprovedARNPatterns:
      {{- range .autoApprovedARNPatterns }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  hub:
    {{- if .Values.fleetConfig.hub.clusterManager }}
    clusterManager:
      featureGates: {{ include "featureGates" (dict "dict" .Values.fleetConfig.hub.clusterManager.featureGates) | quote }}
      purgeOperator: {{ .Values.fleetConfig.hub.clusterManager.purgeOperator }}
      resources: {{- toYaml .Values.fleetConfig.hub.clusterManager.resources | nindent 8 }}
      source:
        bundleVersion: {{ .Values.fleetConfig.source.bundleVersion }}
        registry: {{ .Values.fleetConfig.source.registry }}
    {{- end }}
    {{- if .Values.fleetConfig.hub.singletonControlPlane }}
    singleton: {{- toYaml .Values.fleetConfig.hub.singletonControlPlane | nindent 6 }}
    {{- end }}
    createNamespace: {{ .Values.fleetConfig.hub.createNamespace }}
    force: {{ .Values.fleetConfig.hub.force }}
    kubeconfig: {{- toYaml .Values.fleetConfig.hub.kubeconfig | nindent 6 }}
    apiServer: {{ .Values.fleetConfig.hub.apiServer | quote }}
    ca: {{ .Values.fleetConfig.hub.ca | quote }}
  spokes:
    {{- $spokeFeatureGates := .Values.fleetConfig.spokeFeatureGates }}
    {{- range .Values.fleetConfig.spokes }}
    - name: {{ .name }}
      createNamespace: {{ .createNamespace }}
      syncLabels: {{ .syncLabels }}
      kubeconfig: {{- toYaml .kubeconfig | nindent 8 }}
      proxyCa: {{ .proxyCa | quote }}
      proxyUrl: {{ .proxyUrl | quote }}
      {{- if .clusterARN }}
      clusterARN: {{ .clusterARN | quote }}
      {{- end }}
      klusterlet:
        {{- if and .klusterlet.annotations $.Values.fleetConfig.spokeAnnotations }}
        annotations: {{- toYaml (merge .klusterlet.annotations $.Values.fleetConfig.spokeAnnotations) | nindent 10 }}
        {{- else if .klusterlet.annotations }}
        annotations: {{- toYaml .klusterlet.annotations | nindent 10 }}
        {{- else if $.Values.fleetConfig.spokeAnnotations }}
        annotations: {{- toYaml $.Values.fleetConfig.spokeAnnotations | nindent 10 }}
        {{- end }}
        mode: {{ .klusterlet.mode | quote }}
        purgeOperator: {{ .klusterlet.purgeOperator }}
        featureGates: {{ include "featureGates" (dict "dict" $spokeFeatureGates) | quote }}
        forceInternalEndpointLookup: {{ .klusterlet.forceInternalEndpointLookup }}
        forceInternalEndpointLookupManaged: {{ .klusterlet.forceInternalEndpointLookupManaged }}
        singleton: {{ .klusterlet.singleton }}
        managedClusterKubeconfig: {{- toYaml .klusterlet.managedClusterKubeconfig | nindent 10 }}
        resources: {{- toYaml .klusterlet.resources | nindent 10 }}
        source:
          bundleVersion: {{ $.Values.fleetConfig.source.bundleVersion }}
          registry: {{ $.Values.fleetConfig.source.registry }}
      addOns: {{- toYaml .addOns | nindent 8 }}
    {{- end }}
  addOnConfigs: {{- toYaml .Values.fleetConfig.addOnConfigs | nindent 4 }}
{{- end }}
